name: Build and Deploy Code

on: [push, pull_request]
  # push:
  #   branches: 
  #     - "master"
  # pull_request:
  #   branches: 
  #     - "dev"
jobs:
  # Build:
  #   environment:
  #     name: Testing
  #   runs-on: ubuntu-latest
  #   env:
  #     DB_HOST: ${{secrets.DB_HOST}}
  #     DB_PORT: ${{secrets.DB_PORT}}
  #     DB_NAME: ${{secrets.DB_NAME}}
  #     DB_USER: ${{secrets.DB_USER}}
  #     DB_PW: ${{secrets.DB_PW}}
  #     SECRET_KEY: ${{secrets.SECRET_KEY}}
  #     ALGORITHM: ${{secrets.ALGORITHM}}
  #     TOKEN_MINS_EXPIRE: ${{secrets.TOKEN_MINS_EXPIRE}}
  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: ${{secrets.DB_PW}}
  #         POSTGRES_DB: ${{secrets.DB_NAME}}_test
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #   steps:
  #     - name: pulling git repo
  #       uses: actions/checkout@v4
  #     - name: Install python version 3.12.3
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.12.3'
  #     - name: Install & upgrade pip
  #       run: python3 -m pip install --upgrade pip
  #     - name: Install all dependencies
  #       run: pip install -r requirements.txt
  #     - name: Testing with pytest
  #       run: |
  #         pip install pytest
  #         pytest -v
      
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-            
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     #tags: user/app:latest
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:latest
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      #   # Temp fix
      #   # https://github.com/docker/build-push-action/issues/252
      #   # https://github.com/moby/buildkit/issues/1896
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache  
      
  Deploy:
    runs-on: ubuntu-latest
    #needs: [Build]
    environment:
      name: Production
    steps:
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          key: ${{secrets.PROD_KEY}}
          password: ${{secrets.PROD_PASSWORD}}
          port: 22 #${{secrets.PROD_PORT}}
          script: |
            echo "Good job"
            # cd app/src
            # git pull
            # echo ${{secrets.PROD_PASSWORD}} | sudo -S systemctl restart api